### ISSUE TITLE
Markdown version of the blogpost?

### ISSUE THREAD

**Issue by xplorld** [nicolasbrailo/cpp_exception_handling_abi#1]
Thanks for your awesome blogpost!
It is rather inconvenient to read the black text in deep dark grey background. I'm not sure whether it is from my browser, though I tested in incognito mode and appears to be same. Is this the style you expected?
![image](https://cloud.githubusercontent.com/assets/7023694/25077540/97582e78-235d-11e7-9feb-2401a4e00909.png)

**Comment by nicolasbrailo** [comment]
Thanks for the report @xplorld. That's definitely not how it's supposed to look! The whole css looks broken (the menus shouldn't be ul's). I just tested it in Firefox, Chrome and Android's Chrome and it looks more or less the same as in the screenshot here. Any chance there's an extension on your side breaking the stylesheet? Could you try with a different browser?

![screenshot_2017-04-17_09-40-36](https://cloud.githubusercontent.com/assets/1199441/25082573/064a39f4-2352-11e7-96c6-b7dc8d6706d1.png)

**Comment by xplorld** [comment]
Oh I found the problem.

It turns out to blame my VPN configurations. In China there is a Nation-wide Firewall blocking many of the websites including google.com, wordpress.com and many others. My VPN was in an 'automatic' mode to decide whether go through the VPN or not by a whitelist. Some of the stylesheets (not sure which) was newly blocked but not yet added to the VPN whitelist so could not be fetched. Opening global VPN results in a page looks exactly as your screenshot.

Thanks for your grest post!

**Comment by nicolasbrailo** [comment]
Happy the issue is solved then, and thanks for reading!
