### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rdrpenguin04** [nicolasbrailo/cpp_exception_handling_abi#4]
I'm working on a libstdc++ reimplementation, and I was wondering if I could base my code off of this one. I looked for a license to see if I could, but I didn't see one.

Could you provide a license or this, or otherwise specify that all rights are reserved? That would be helpful to me and other people trying to do similar things in the future!

**Comment by nicolasbrailo** [comment]
Sure, I'll add one shortly (some CC variant).

I'm happy you find this project useful, and I'm sure you are already aware, but just to be safe: this project is meant as a didactic device and as such prioritizes opportunities to learn over production code. It lacks portability, it's full of security issues and I'm sure the performance is terrible. Please keep this in mind if you intend to write any production ready code based on this project and its articles. libstdc++ may be a safer starting point.

**Comment by rdrpenguin04** [comment]
Thank you!

I have one very specific reason I'm not basing my code on libstdc++, and that's because I'm making my reimplementation with a more permissive license. Using libstdc++ code immediately forces my implementation to be LGPL or stricter.

Anyways, thank you for adding a license!
